name: blake2
description: >-
  Pure Dart implementations of the BLAKE2b and
  BLAKE2s cryptographic hashing functions.
version: 0.1.1
homepage: https://github.com/james-alex/blake2

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  test: ^1.6.5
  effective_dart: ^1.0.0
